---
- hosts: all
  become: true
  tasks:

  - name: install pip3, python3 and Java open-jdk for ubuntu
    apt:
      name:
       - pipsi
       - python3-pip
       - openjdk-11-jdk
      state: latest
      update_cache: yes
      when: ansible_distribution == "Ubuntu"

  - name: install pip3, python3 and Java open-jdk
    dnf:
       name: 
        - python3-pip
        - python3
        - java-1.8.-openjdk
       state: latest
       update_cache: yes
    when: ansible_distribution == "CentOS"
 
- hosts: all
  become: true
  tasks:

  - shell: echo 'joshua' 
    register: server1
  - debug: msg ="motd by {{server1.stdout }} "
 
  - shell: echo 'joshualomibao'
    register: server2
  - debug: msg="user {{server2.stdout}} "

